name: 建置並部署靜態網站

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v2

    - name: 設定 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 安裝 Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1

    - name: 安裝依賴
      run: poetry install --no-root

    - name: 執行單元測試
      run: poetry run pytest -v

    - name: 生成靜態網站
      run: poetry run python src/main.py
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        SHEET_NAME: ${{ secrets.SHEET_NAME }}
        OUTPUT_DIR: dist

    - name: 部署到 Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME || 'pen-power-recall' }}
        directory: dist
        branch: main
